#!/bin/sh

set -e

running_in_container()
{
    type systemd-detect-virt >/dev/null 2>&1 && systemd-detect-virt --quiet --container
}

install_i386_pc() {
    local basedev=$(grub-probe -t device /boot/ | sed -Ee 's/[0-9]+$//' -e 's/([0-9])p$/\1/')
    grub-install --target=i386-pc "$basedev"
}

install_x86_64_efi() {
    # No support for shim yet, install also into removable location
    if [ -d /boot/efi ]; then

	# Force any old EFI stuff tagged incorrectly as Debian
	rm -rf /boot/efi/EFI/debian

	# Install the new binary
        grub-install --target=x86_64-efi --no-nvram --force-extra-removable

    else
        echo "No EFI directory found, skipping EFI grub-install"
    fi
}

case "$1" in
    configure)
	cp /usr/share/grub-cloud/grub /etc/default/grub
        if ! running_in_container; then
            install_i386_pc
            install_x86_64_efi
        fi
        update-grub
    ;;

    triggered)
        if ! running_in_container; then
            install_i386_pc
            install_x86_64_efi
        fi
    ;;
esac

#DEBHELPER#

exit 0
