#!/bin/sh

set -e

running_in_container()
{
    type systemd-detect-virt >/dev/null 2>&1 && systemd-detect-virt --quiet --container
}

install_arm64_efi() {
    # No support for shim yet, install also into removable location
    if [ -d /boot/efi ]; then

	# Force any old EFI stuff tagged incorrectly as Debian
	rm -rf /boot/efi/EFI/debian

	# Install the new binary
        grub-install --target=arm64-efi --no-nvram --force-extra-removable

    else
        echo "No EFI directory found, skipping EFI grub-install"
    fi
}

case "$1" in
    configure)
	cp /usr/share/grub-cloud/grub /etc/default/grub
        if ! running_in_container; then
            install_arm64_efi
        fi
        update-grub
    ;;

    triggered)
        if ! running_in_container; then
            install_arm64_efi
        fi
    ;;
esac

#DEBHELPER#

exit 0
